from __future__ import annotations

import argparse
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlsplit

from tools import logger
from tools.config import (
    ConfigLoadError,
    ConfigValidationError,
    load_runtime_config,
    redact_text,
    resolve_configuration,
    validate_configuration,
)
from tools.profiles import runtime as profile_runtime

ROOT = Path(__file__).resolve().parents[2]
BACKEND_DIR = ROOT / "backend"


@dataclass(frozen=True, slots=True)
class DatabaseCheck:
    name: str
    status: str
    message: str


def configure_parser(parser: argparse.ArgumentParser) -> None:
    parser.set_defaults(db_parser=parser)
    subparsers = parser.add_subparsers(dest="db_command", title="database actions", metavar="<action>")

    doctor = subparsers.add_parser("doctor", help="validate database configuration without changing data")
    doctor.add_argument("--connect", action="store_true", help="also execute a read-only SELECT 1 connection probe")

    subparsers.add_parser("current", help="show the current Alembic revision")

    upgrade = subparsers.add_parser("upgrade", help="apply Alembic migrations")
    upgrade.add_argument("revision", nargs="?", default="head", help="target revision (default: head)")

    downgrade = subparsers.add_parser("downgrade", help="revert Alembic migrations")
    downgrade.add_argument("revision", nargs="?", default="-1", help="target revision (default: -1)")

    revision = subparsers.add_parser("revision", help="create an autogenerated Alembic revision")
    revision.add_argument("--message", "-m", required=True, help="migration description")


def _backend_python() -> Path:
    candidates = [
        BACKEND_DIR / ".venv" / "Scripts" / "python.exe",
        BACKEND_DIR / ".venv" / "bin" / "python",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    # Production containers run the CLI from the image-level virtualenv instead of
    # creating a mutable backend/.venv inside the read-only application image.
    if sys.prefix != sys.base_prefix:
        return Path(sys.executable)
    return candidates[0] if sys.platform == "win32" else candidates[1]


def _run_probe(script: str) -> subprocess.CompletedProcess[str]:
    python = _backend_python()
    if not python.exists():
        return subprocess.CompletedProcess([str(python)], 127, "", "backend virtualenv is missing")
    environment = os.environ.copy()
    try:
        profile = profile_runtime.active_profile(ROOT)
        config = load_runtime_config(profile, project_root=ROOT)
        environment.update(config.backend_environment())
    except (ConfigLoadError, ConfigValidationError):
        pass
    return subprocess.run(
        [str(python), "-c", script],
        cwd=BACKEND_DIR,
        env=environment,
        text=True,
        capture_output=True,
        check=False,
    )


def _feature_error() -> str | None:
    profile = profile_runtime.active_profile(ROOT)
    if profile.has_feature("database"):
        return None
    return "Database feature is not enabled for this project."


def _redact_database_url(text: str) -> str:
    database_url = os.getenv("DATABASE_URL")
    if database_url is None:
        try:
            profile = profile_runtime.active_profile(ROOT)
            database_url = load_runtime_config(profile, project_root=ROOT).database_url
        except (ConfigLoadError, ConfigValidationError):
            database_url = None
    return redact_text(text, {"DATABASE_URL": database_url})


def _configuration_checks(*, connect: bool) -> list[DatabaseCheck]:
    checks: list[DatabaseCheck] = []
    feature_error = _feature_error()
    if feature_error:
        return [DatabaseCheck("feature", "FAIL", feature_error)]
    checks.append(DatabaseCheck("feature", "OK", "database feature enabled"))

    profile = profile_runtime.active_profile(ROOT)
    try:
        resolved = resolve_configuration(profile, project_root=ROOT)
    except ConfigLoadError as exc:
        checks.append(DatabaseCheck("configuration", "FAIL", str(exc)))
        return checks
    non_database_issues = [issue for issue in validate_configuration(resolved) if issue.name != "DATABASE_URL"]
    if non_database_issues:
        checks.append(
            DatabaseCheck(
                "configuration",
                "FAIL",
                "; ".join(f"{issue.name}: {issue.message}" for issue in non_database_issues),
            )
        )
        return checks

    database_url = (resolved.value("DATABASE_URL") or "").strip()
    if not database_url:
        checks.append(DatabaseCheck("DATABASE_URL", "FAIL", "not set in the process environment"))
        return checks

    try:
        parsed = urlsplit(database_url)
        hostname = parsed.hostname
    except ValueError:
        checks.append(DatabaseCheck("DATABASE_URL", "FAIL", "URL structure is invalid"))
        return checks
    if not parsed.scheme:
        checks.append(DatabaseCheck("DATABASE_URL", "FAIL", "missing SQLAlchemy driver scheme"))
        return checks

    if profile.has_feature("postgres") and parsed.scheme != "postgresql+psycopg":
        checks.append(
            DatabaseCheck(
                "DATABASE_URL",
                "FAIL",
                "postgres feature requires the 'postgresql+psycopg' driver scheme",
            )
        )
        return checks
    if profile.has_feature("postgres") and (not hostname or not parsed.path.strip("/")):
        checks.append(DatabaseCheck("DATABASE_URL", "FAIL", "PostgreSQL URL must include a host and database name"))
        return checks
    checks.append(DatabaseCheck("DATABASE_URL", "OK", f"driver scheme is {parsed.scheme}"))

    imports = ["sqlalchemy", "alembic"]
    if profile.has_feature("postgres"):
        imports.append("psycopg")
    probe = _run_probe("import " + ", ".join(imports))
    if probe.returncode != 0:
        detail = (probe.stderr or probe.stdout).strip() or f"exit code {probe.returncode}"
        checks.append(DatabaseCheck("dependencies", "FAIL", f"imports failed: {detail}"))
        return checks
    checks.append(DatabaseCheck("dependencies", "OK", f"importable: {', '.join(imports)}"))

    if connect:
        connection_probe = _run_probe(
            "from sqlalchemy import create_engine, text; "
            "import os; "
            "engine=create_engine(os.environ['DATABASE_URL'], pool_pre_ping=True); "
            "connection=engine.connect(); "
            "assert connection.scalar(text('SELECT 1')) == 1; "
            "connection.close(); engine.dispose()"
        )
        if connection_probe.returncode != 0:
            detail = (connection_probe.stderr or connection_probe.stdout).strip() or "connection failed"
            detail = _redact_database_url(detail)
            checks.append(DatabaseCheck("connection", "FAIL", detail.splitlines()[-1]))
        else:
            checks.append(DatabaseCheck("connection", "OK", "read-only SELECT 1 succeeded"))

    return checks


def _doctor(*, connect: bool) -> int:
    checks = _configuration_checks(connect=connect)
    failed = False
    for check in checks:
        logger.status(check.status, f"db:{check.name:<14} {check.message}")
        failed = failed or check.status == "FAIL"
    return 1 if failed else 0


def _migration_preflight() -> bool:
    checks = _configuration_checks(connect=False)
    failures = [check.message for check in checks if check.status == "FAIL"]
    if not failures:
        return True
    for message in failures:
        logger.fail(message)
    return False


def _run_alembic(arguments: list[str]) -> int:
    if not _migration_preflight():
        return 1

    command = [str(_backend_python()), "-m", "alembic", "-c", "alembic.ini", *arguments]
    environment = os.environ.copy()
    try:
        profile = profile_runtime.active_profile(ROOT)
        environment.update(load_runtime_config(profile, project_root=ROOT).backend_environment())
    except (ConfigLoadError, ConfigValidationError) as exc:
        logger.fail(f"Invalid database configuration: {exc}")
        return 1
    completed = subprocess.run(
        command,
        cwd=BACKEND_DIR,
        env=environment,
        text=True,
        capture_output=True,
        check=False,
    )
    if completed.stdout:
        safe_stdout = _redact_database_url(completed.stdout)
        print(safe_stdout, end="" if safe_stdout.endswith("\n") else "\n")
    if completed.returncode != 0:
        detail = (completed.stderr or "").strip() or f"exit code {completed.returncode}"
        detail = _redact_database_url(detail)
        logger.fail(f"Alembic command failed: {detail}")
        return completed.returncode or 1
    logger.ok(f"Alembic command completed: {' '.join(arguments)}")
    return 0


def main(args: argparse.Namespace) -> int:
    command = getattr(args, "db_command", None)
    if command is None:
        args.db_parser.print_help()
        return 0
    if command == "doctor":
        return _doctor(connect=bool(args.connect))
    if command == "current":
        return _run_alembic(["current"])
    if command == "upgrade":
        return _run_alembic(["upgrade", args.revision])
    if command == "downgrade":
        return _run_alembic(["downgrade", args.revision])
    if command == "revision":
        return _run_alembic(["revision", "--autogenerate", "-m", args.message])
    logger.fail(f"Unknown database command: {command}")
    return 2
