"""Profile-driven, project-safe tooling integration primitives."""

from tools.integration.assets import (
    AssetError,
    copy_asset,
    copy_packaged_asset,
    read_asset,
    read_packaged_asset,
)
from tools.integration.migrations import (
    REGISTRY,
    ConditionKind,
    Migration,
    MigrationApplicability,
    MigrationCondition,
    MigrationRegistry,
    MigrationRun,
    StructuredKeyAllowlist,
    build_migration_run,
    validate_postconditions,
    validate_preconditions,
)
from tools.integration.model import (
    UNSET,
    Conflict,
    Finding,
    FindingStatus,
    IntegrationError,
    IntegrationPlan,
    IntegrationResult,
    MigrationError,
    Operation,
    OperationKind,
    Ownership,
    PlanningError,
    ReportError,
    StructuredChange,
    VerificationError,
    VerificationResult,
)
from tools.integration.planner import (
    DesiredProfile,
    DesiredResource,
    ObservedResource,
    create_plan,
)
from tools.integration.report import plan_to_dict, verification_to_dict, write_report
from tools.integration.transaction import (
    TransactionRequest,
    apply_plan,
    apply_transaction,
)
from tools.integration.verify import (
    VerificationAdapter,
    aggregate_results,
    verify_adapters,
)

__all__ = [
    "REGISTRY",
    "UNSET",
    "AssetError",
    "ConditionKind",
    "Conflict",
    "DesiredProfile",
    "DesiredResource",
    "Finding",
    "FindingStatus",
    "IntegrationError",
    "IntegrationPlan",
    "IntegrationResult",
    "Migration",
    "MigrationApplicability",
    "MigrationCondition",
    "MigrationError",
    "MigrationRegistry",
    "MigrationRun",
    "ObservedResource",
    "Operation",
    "OperationKind",
    "Ownership",
    "PlanningError",
    "ReportError",
    "StructuredChange",
    "StructuredKeyAllowlist",
    "TransactionRequest",
    "VerificationAdapter",
    "VerificationError",
    "VerificationResult",
    "aggregate_results",
    "apply_plan",
    "apply_transaction",
    "build_migration_run",
    "copy_asset",
    "copy_packaged_asset",
    "create_plan",
    "plan_to_dict",
    "read_asset",
    "read_packaged_asset",
    "validate_postconditions",
    "validate_preconditions",
    "verification_to_dict",
    "verify_adapters",
    "write_report",
]
