from __future__ import annotations

import os
from pathlib import Path, PurePosixPath, PureWindowsPath

from tools import logger
from tools.core.filesystem import (
    FilesystemSafetyError,
    atomic_write_text,
    ensure_directory,
    read_regular_text,
    safe_join,
    validate_root,
)
from tools.tauri import common, paths

_ORIGIN_FILE_NAME = ".tauri-dev-cache-origin"
_RERUN_IF_CHANGED_PREFIX = "cargo:rerun-if-changed="
_PLUGIN_PERMISSION_FAILURE = "failed to read plugin permissions:"
_AUTOGENERATED_PERMISSION_PATH = "/permissions/app/autogenerated/"


def prepare_dev_cache() -> bool:
    """Clear relocated Tauri dev artifacts before they can break a build."""
    target_dir = dev_target_dir()
    expected_config = current_tauri_config_path()
    try:
        recorded_config = _read_origin(target_dir)
    except FilesystemSafetyError as exc:
        logger.fail(f"Refusing unsafe Tauri dev-cache origin: {exc}")
        return False

    if recorded_config is not None and recorded_config != expected_config:
        return recover_dev_cache(
            "Detected Tauri dev artifacts from another project location."
        )
    if recorded_config is None and _has_only_stale_config_references(
        target_dir, expected_config
    ):
        return recover_dev_cache(
            "Detected relocated Tauri dev artifacts from Cargo metadata."
        )

    return _write_origin(target_dir, expected_config)


def recover_dev_cache(reason: str) -> bool:
    """Clear only the Cargo development profile and record its current origin."""
    target_dir = dev_target_dir()
    try:
        _safe_target_dir(target_dir, create=True)
    except FilesystemSafetyError as exc:
        logger.fail(f"Refusing unsafe Cargo target directory: {exc}")
        return False
    logger.warn(f"{reason} Clearing Cargo development artifacts before retrying Tauri.")
    result = common.run_command(_cargo_clean_command(target_dir), cwd=paths.ROOT)
    if result.returncode != 0:
        details = common.tail(f"{result.stdout}\n{result.stderr}")
        logger.fail(f"Could not clear stale Tauri development artifacts: {details}")
        return False

    if not _write_origin(target_dir, current_tauri_config_path()):
        return False
    logger.ok("Stale Tauri development artifacts cleared.")
    return True


def is_plugin_permission_cache_failure(output: str) -> bool:
    """Recognize the Tauri diagnostic caused by stale generated permissions."""
    normalized = output.replace("\\", "/").lower()
    return (
        _PLUGIN_PERMISSION_FAILURE in normalized
        and _AUTOGENERATED_PERMISSION_PATH in normalized
    )


def dev_target_dir() -> Path:
    configured_target = os.environ.get("CARGO_TARGET_DIR")
    if not configured_target:
        return paths.TAURI_DIR / "target"

    target_dir = Path(configured_target).expanduser()
    if target_dir.is_absolute():
        return target_dir
    return paths.ROOT / target_dir


def current_tauri_config_path() -> str:
    return str((paths.TAURI_DIR / "tauri.conf.json").resolve())


def _cargo_clean_command(target_dir: Path) -> list[str]:
    return [
        "cargo",
        "clean",
        "--profile",
        "dev",
        "--manifest-path",
        str(paths.TAURI_DIR / "Cargo.toml"),
        "--target-dir",
        str(target_dir),
    ]


def _has_only_stale_config_references(target_dir: Path, expected_config: str) -> bool:
    references = _tauri_config_references(target_dir)
    return bool(references) and expected_config not in references


def _tauri_config_references(target_dir: Path) -> set[str]:
    build_dir = target_dir / "debug" / "build"
    if not build_dir.is_dir():
        return set()

    references: set[str] = set()
    for output_file in build_dir.glob("*/output"):
        try:
            output = output_file.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        references.update(_tauri_config_paths(output))
    return references


def _tauri_config_paths(output: str) -> set[str]:
    paths_in_output: set[str] = set()
    for line in output.splitlines():
        if not line.startswith(_RERUN_IF_CHANGED_PREFIX):
            continue
        candidate = line.removeprefix(_RERUN_IF_CHANGED_PREFIX)
        reference = _absolute_tauri_config_reference(candidate)
        if reference is not None:
            paths_in_output.add(reference)
    return paths_in_output


def _absolute_tauri_config_reference(value: str) -> str | None:
    native = Path(value)
    if native.is_absolute() and native.name.casefold() == "tauri.conf.json":
        return str(native.resolve())

    for path_type in (PurePosixPath, PureWindowsPath):
        foreign = path_type(value)
        if foreign.is_absolute() and foreign.name.casefold() == "tauri.conf.json":
            return str(foreign)
    return None


def _origin_path(target_dir: Path) -> Path:
    return target_dir / _ORIGIN_FILE_NAME


def _safe_target_dir(target_dir: Path, *, create: bool) -> Path | None:
    absolute = Path(os.path.abspath(target_dir))
    project_root = validate_root(paths.ROOT)
    try:
        relative = absolute.relative_to(project_root).as_posix()
    except ValueError:
        parent = validate_root(absolute.parent)
        if not create and not absolute.exists() and not absolute.is_symlink():
            return None
        return (
            ensure_directory(parent, absolute.name)
            if create
            else safe_join(parent, absolute.name, require_exists=True)
        )
    if not relative:
        return project_root
    if not create and not absolute.exists() and not absolute.is_symlink():
        return None
    return (
        ensure_directory(project_root, relative)
        if create
        else safe_join(project_root, relative, require_exists=True)
    )


def _read_origin(target_dir: Path) -> str | None:
    safe_target = _safe_target_dir(target_dir, create=False)
    if safe_target is None:
        return None
    origin = safe_target / _ORIGIN_FILE_NAME
    if not origin.exists() and not origin.is_symlink():
        return None
    value = read_regular_text(
        origin,
        root=safe_target,
        label="Tauri dev-cache origin",
    ).strip()
    return value or None


def _write_origin(target_dir: Path, config_path: str) -> bool:
    try:
        safe_target = _safe_target_dir(target_dir, create=True)
        assert safe_target is not None
        atomic_write_text(
            safe_target / _ORIGIN_FILE_NAME,
            f"{config_path}\n",
            root=safe_target,
        )
    except (FilesystemSafetyError, OSError) as exc:
        logger.fail(f"Could not record the Tauri dev-cache origin safely: {exc}")
        return False
    return True
