from __future__ import annotations

import os
from pathlib import Path

from tools import logger
from tools.tauri import common, paths

_ORIGIN_FILE_NAME = ".tauri-dev-cache-origin"
_RERUN_IF_CHANGED_PREFIX = "cargo:rerun-if-changed="
_PLUGIN_PERMISSION_FAILURE = "failed to read plugin permissions:"
_AUTOGENERATED_PERMISSION_PATH = "/permissions/app/autogenerated/"


def prepare_dev_cache() -> bool:
    """Clear relocated Tauri dev artifacts before they can break a build."""
    target_dir = dev_target_dir()
    expected_config = current_tauri_config_path()
    recorded_config = _read_origin(target_dir)

    if recorded_config is not None and recorded_config != expected_config:
        return recover_dev_cache("Detected Tauri dev artifacts from another project location.")
    if recorded_config is None and _has_only_stale_config_references(target_dir, expected_config):
        return recover_dev_cache("Detected relocated Tauri dev artifacts from Cargo metadata.")

    _write_origin(target_dir, expected_config)
    return True


def recover_dev_cache(reason: str) -> bool:
    """Clear only the Cargo development profile and record its current origin."""
    target_dir = dev_target_dir()
    logger.warn(f"{reason} Clearing Cargo development artifacts before retrying Tauri.")
    result = common.run_command(_cargo_clean_command(target_dir), cwd=paths.ROOT)
    if result.returncode != 0:
        details = common.tail(f"{result.stdout}\n{result.stderr}")
        logger.fail(f"Could not clear stale Tauri development artifacts: {details}")
        return False

    _write_origin(target_dir, current_tauri_config_path())
    logger.ok("Stale Tauri development artifacts cleared.")
    return True


def is_plugin_permission_cache_failure(output: str) -> bool:
    """Recognize the Tauri diagnostic caused by stale generated permissions."""
    normalized = output.replace("\\", "/").lower()
    return _PLUGIN_PERMISSION_FAILURE in normalized and _AUTOGENERATED_PERMISSION_PATH in normalized


def dev_target_dir() -> Path:
    configured_target = os.environ.get("CARGO_TARGET_DIR")
    if not configured_target:
        return paths.TAURI_DIR / "target"

    target_dir = Path(configured_target).expanduser()
    if target_dir.is_absolute():
        return target_dir
    return paths.ROOT / target_dir


def current_tauri_config_path() -> str:
    return str((paths.TAURI_DIR / "tauri.conf.json").resolve())


def _cargo_clean_command(target_dir: Path) -> list[str]:
    return [
        "cargo",
        "clean",
        "--profile",
        "dev",
        "--manifest-path",
        str(paths.TAURI_DIR / "Cargo.toml"),
        "--target-dir",
        str(target_dir),
    ]


def _has_only_stale_config_references(target_dir: Path, expected_config: str) -> bool:
    references = _tauri_config_references(target_dir)
    return bool(references) and expected_config not in references


def _tauri_config_references(target_dir: Path) -> set[str]:
    build_dir = target_dir / "debug" / "build"
    if not build_dir.is_dir():
        return set()

    references: set[str] = set()
    for output_file in build_dir.glob("*/output"):
        try:
            output = output_file.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        references.update(_tauri_config_paths(output))
    return references


def _tauri_config_paths(output: str) -> set[str]:
    paths_in_output: set[str] = set()
    for line in output.splitlines():
        if not line.startswith(_RERUN_IF_CHANGED_PREFIX):
            continue
        candidate = Path(line.removeprefix(_RERUN_IF_CHANGED_PREFIX))
        if candidate.is_absolute() and candidate.name == "tauri.conf.json":
            paths_in_output.add(str(candidate.resolve()))
    return paths_in_output


def _origin_path(target_dir: Path) -> Path:
    return target_dir / _ORIGIN_FILE_NAME


def _read_origin(target_dir: Path) -> str | None:
    try:
        value = _origin_path(target_dir).read_text(encoding="utf-8").strip()
    except FileNotFoundError:
        return None
    except OSError:
        return None
    return value or None


def _write_origin(target_dir: Path, config_path: str) -> None:
    try:
        target_dir.mkdir(parents=True, exist_ok=True)
        _origin_path(target_dir).write_text(f"{config_path}\n", encoding="utf-8")
    except OSError:
        logger.warn("Could not record the Tauri dev-cache origin; stale-cache recovery remains available.")
